### ISSUE TITLE
is_string_like use in mapviz

### ISSUE THREAD

**Issue by aclong** [CxAalto/gtfspy#14]
I'm currently trying to use the mapviz functionality and get an error with the use of is_string_like as it is deprecated in the version of matplotlib.cbook that matplotlib-scalebar uses. 

I have pip installed from requirements inside a specific conda environment, using python 3.5.5

Should a specific version of matplotlib-scalebar be used?

![is_string_like_error](https://user-images.githubusercontent.com/37698923/50228115-22cc2b80-039f-11e9-8ab8-096e124fc870.png)

**Comment by jweckstr** [comment]
Seems like you need to update matplotlib-scalebar to version 0.4.1 or above. That version have adressed the described issue: "Fix deprecated usage of is_string_like"

https://pypi.org/project/matplotlib-scalebar/

Let us know if the problem persists!

**Comment by aclong** [comment]
Thanks it worked!

I updated matlpotlib-scalebar, it had previously been restricted by the conda environment I created from  requirements.txt and had to override warnings about it being dependencies due to it being more recent than other package versions used.
