### ISSUE TITLE
 I can't install gtfspy.

### ISSUE THREAD

**Issue by chingui** [CxAalto/gtfspy#15]
HELLO! i m trying to install gtfspy on my computer but i cannot , when i try i get this error:
https://github.com/CxAalto/gtfspy/issues/created_by/rmkujala. Please help me a need it for my final project.
thanks,
JC

**Comment by jweckstr** [comment]
Can you please provide a bit more detail. What exactly is the error message you are receiving (now you are only giving a link to the issues page)? What operating system are you using? How are you using to install gtfspy?`

Best regards,
Christoffer

**Comment by alifa-putri** [comment]
Hi, I keep getting the following message when I try to install gtfspy. Do you have any suggestions? 

ERROR: Command errored out with exit status 1:
 command: 'c:\users\auap501456\appdata\local\programs\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AUAP50~1\\AppData\\Local\\Temp\\pip-install-bz3qixey\\shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\AUAP50~1\\AppData\\Local\\Temp\\pip-install-bz3qixey\\shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\AUAP50~1\AppData\Local\Temp\pip-install-bz3qixey\shapely\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AUAP50~1\AppData\Local\Temp\pip-install-bz3qixey\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\AUAP50~1\AppData\Local\Temp\pip-install-bz3qixey\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\users\auap501456\appdata\local\programs\python\python37-32\lib\ctypes\__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rmkujala** [comment]
Hi,

It seems that you're trying to run gtfspy on Windows, which unfortunately is not currently supported.

BR,
Rainer

**Comment by jweckstr** [comment]
I think it is possible to get gtfspy working on Windows too, however, you will need to manually install some dependencies. In this case I think you are missing shapely, which can be installed using the instructions given here: https://towardsdatascience.com/install-shapely-on-windows-72b6581bb46c

**Comment by evelyn9191** [comment]
I had the same problem and the suggestion from @jweckstr helped. Thanks!
